apiVersion: chaosblade.io/v1alpha1
kind: ChaosBlade
metadata:
  name: test-configmap-delete-with-name
spec:
  experiments:
  - scope: pod
    target: pod
    action: configmapdelete
    desc: "Delete specified ConfigMap ns-config to simulate Pod startup failure"
    matchers:
    - name: names
      value:
      - "kone-app-service-69866bbc7d-z4qxw"
    - name: namespace
      value:
      - "ark-system"
    - name: configmap-name
      value:
      - "ns-config"
